// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class NoteService {
    /**
     * @param data The data for the request.
     * @param data.entryId
     * @returns NoteDetails OK
     * @throws ApiError
     */
    public static getNoteByEntryId(data: $OpenApiTs['/notes/{entryId}']['get']['req']): CancelablePromise<$OpenApiTs['/notes/{entryId}']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/notes/{entryId}',
            path: {
                entryId: data.entryId
            },
            errors: {
                403: 'Forbidden'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.entryId
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static putNote(data: $OpenApiTs['/notes/{entryId}']['put']['req']): CancelablePromise<$OpenApiTs['/notes/{entryId}']['put']['res'][200]> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/notes/{entryId}',
            path: {
                entryId: data.entryId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.noteId
     * @returns SubscribeOutput OK
     * @throws ApiError
     */
    public static subscribe(data: $OpenApiTs['/notes/{noteId}/subscribe']['post']['req']): CancelablePromise<$OpenApiTs['/notes/{noteId}/subscribe']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/notes/{noteId}/subscribe',
            path: {
                noteId: data.noteId
            }
        });
    }
    
    /**
     * @returns NoteSummary OK
     * @throws ApiError
     */
    public static getNotes(): CancelablePromise<$OpenApiTs['/notes']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/notes'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.entryId
     * @returns ResponseMessage OK
     * @throws ApiError
     */
    public static deleteByEntryId(data: $OpenApiTs['/notes']['delete']['req']): CancelablePromise<$OpenApiTs['/notes']['delete']['res'][200]> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/notes',
            query: {
                entryId: data.entryId
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.noteId
     * @returns NoteDetails OK
     * @throws ApiError
     */
    public static getNoteByNoteId(data: $OpenApiTs['/notes/{noteId}']['get']['req']): CancelablePromise<$OpenApiTs['/notes/{noteId}']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/notes/{noteId}',
            path: {
                noteId: data.noteId
            },
            errors: {
                403: 'Forbidden'
            }
        });
    }
    
}

export class ReaderService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ResponseMessage OK
     * @throws ApiError
     */
    public static createReader(data: $OpenApiTs['/readers']['post']['req']): CancelablePromise<$OpenApiTs['/readers']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/readers',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.readerId
     * @param data.activationLinkId
     * @returns ResponseMessage OK
     * @throws ApiError
     */
    public static activate(data: $OpenApiTs['/readers/{readerId}/activations/{activationLinkId}']['post']['req']): CancelablePromise<$OpenApiTs['/readers/{readerId}/activations/{activationLinkId}']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/readers/{readerId}/activations/{activationLinkId}',
            path: {
                readerId: data.readerId,
                activationLinkId: data.activationLinkId
            },
            errors: {
                403: 'Forbidden'
            }
        });
    }
    
}

export class PasswordResetService {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ResponseMessage OK
     * @throws ApiError
     */
    public static reset(data: $OpenApiTs['/password_reset']['post']['req']): CancelablePromise<$OpenApiTs['/password_reset']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/password_reset',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ResponseMessage OK
     * @throws ApiError
     */
    public static sendLink(data: $OpenApiTs['/password_reset/send_link']['post']['req']): CancelablePromise<$OpenApiTs['/password_reset/send_link']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/password_reset/send_link',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class TokenService {
    /**
     * @param data The data for the request.
     * @param data.username
     * @param data.password
     * @returns OAuth2Token OK
     * @throws ApiError
     */
    public static token(data: $OpenApiTs['/oauth/token']['post']['req']): CancelablePromise<$OpenApiTs['/oauth/token']['post']['res'][200]> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/oauth/token',
            query: {
                username: data.username,
                password: data.password
            },
            errors: {
                401: 'Unauthorized'
            }
        });
    }
    
}

export class InfoService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static info(): CancelablePromise<$OpenApiTs['/info']['get']['res'][200]> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/info'
        });
    }
    
}