name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
jobs:
  test:
    uses: making/workflows/.github/workflows/maven-unit-test.yaml@main
    with:
      e2e_test: true
      test_url_1: http://localhost:8080
      test_url_2: http://localhost:8080/entries/412
  build-jvm-image:
    needs: test
    uses: making/workflows/.github/workflows/build-docker-image-maven-jvm.yaml@main
    with:
      image_name: image_jvm
      image_file: image.yaml
  build-native-image:
    needs: test
    uses: making/workflows/.github/workflows/build-docker-image-maven-native.yaml@main
    with:
      image_name: image_native
      image_file: image_native.yaml
      e2e_test: true
      test_url_1: http://localhost:8080
      test_url_2: http://localhost:8080/entries/412
  save-image-jvm:
    needs: build-jvm-image
    uses: making/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: image_jvm
      image_file: image.yaml
  save-image-native:
    needs: build-native-image
    uses: making/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: image_native
      image_file: image_native.yaml